import "@/styles/globals.scss";
import ReduxProvider from "@/store/Provider";
import BootstrapClient from "../components/BootstrapClient";
import Footer from "@/components/Common/Footer";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js App Router conversion",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <ReduxProvider>
          <div className="mainbody">{children}</div>
          <BootstrapClient />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
