export const content = {
  en: {
    // Navigation
    nav: {
      home: "Home",
      categories: "Categories",
      brands: "Brands",
      deals: "Deals",
      clearance: "Clearance",
      sellWithUs: "Sell With Us",
      trackOrder: "Track Your Order",
      myAccount: "My Account",
      myOrders: "My Orders",
      myWishlist: "My Wishlist",
      cart: "Cart",
      login: "Login",
      logout: "Logout",
      register: "Register",
      search: "Search",
      searchPlaceholder: "Search for products...",
      deliverTo: "Deliver to",
      downloadApp: "Download App",
    },

    // Footer
    footer: {
      aboutUs: "About Ourshopee",
      connectWithUs: "Connect with us",
      enterYourMail: "Enter Your Mail",
      keepInTouch: "Keep in Touch",
      customerService: "Customer Service",
      quickLinks: "Quick Links",
      categories: "Categories",
      information: "Information",
      aboutCompany:
        "UAE and Beyond! Established in 2015, Ourshopee.com has proudly established itself as a prominent and rapidly growing online shopping platform in the region...",
      contactUs: "Contact Us",
      faqs: "FAQs",
      privacyPolicy: "Privacy Policy",
      termsAndConditions: "Terms and Conditions",
      returnPolicy: "Return Policy",
      returnAndReplacementPolicy: "Return and Replacement Policy",
      sitemap: "Sitemap",
      affiliateProgram: "Affiliate Program",
      sellWithUs: "Sell With Us",
      placeComplaint: "Place a Complaint",
      manageComplaint: "Manage Complaint",
      complaints: "Complaints",
      trackYourOrder: "Track Your Order",
      changePassword: "Change Password",
      deliveryAddress: "Delivery Address",
      address: "Address",
      onboarding: "Onboarding",
    },

    // Common Buttons and Actions
    buttons: {
      addToCart: "Add to Cart",
      buyNow: "Buy Now",
      viewDetails: "View Details",
      addToWishlist: "Add to Wishlist",
      removeFromWishlist: "Remove from Wishlist",
      proceedToCheckout: "Proceed to Checkout",
      continueShopping: "Continue Shopping",
      placeOrder: "Place Order",
      apply: "Apply",
      submit: "Submit",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      update: "Update",
      confirm: "Confirm",
      back: "Back",
      next: "Next",
      previous: "Previous",
      close: "Close",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      clear: "Clear",
      reset: "Reset",
      loadMore: "Load More",
      showMore: "Show More",
      showLess: "Show Less",
      select: "Select",
      remove: "Remove",
      viewAll: "View All",
    },

    // Page Titles
    pages: {
      home: "Home",
      aboutUs: "About Us",
      aboutOurshopee: "About Ourshopee",
      contactUs: "Contact Us",
      faqs: "FAQs",
      privacyPolicy: "Privacy Policy",
      termsAndConditions: "Terms and Conditions",
      returnPolicy: "Return Policy",
      returnAndReplacementPolicy: "Return and Replacement Policy",
      sitemap: "Sitemap",
      affiliateProgram: "Affiliate Program",
      sellWithUs: "Sell With Us",
      seller: "Seller",
      complaints: "Complaints",
      placeComplaint: "Place a Complaint",
      manageComplaint: "Manage Complaint",
      successComplaint: "Success Complaint",
      trackYourOrder: "Track Your Order",
      trackOrderById: "Track Order by ID",
      trackOrderByReferenceId: "Track Order by Reference ID",
      myAccount: "My Account",
      myOrders: "My Orders",
      myWishlist: "My Wishlist",
      changePassword: "Change Password",
      deliveryAddress: "Delivery Address",
      address: "Address",
      cart: "Cart",
      checkout: "Checkout",
      payment: "Payment",
      order: "Order",
      brands: "Brands",
      categories: "Categories",
      productsCategory: "Products Category",
      productsSubcategory: "Products Subcategory",
      clearance: "Clearance",
      deals: "Deals",
      dealsOfTheDay: "Deals of the Day",
      bundleDeals: "Bundle Deals",
      perfumes: "Perfumes",
      searchResult: "Search Result",
      onboarding: "Onboarding",
      notFound: "Page Not Found",
      mobileFest: "Mobile Fest",
      timeFest: "Time Fest",
      tvSuperSale: "TV Super Sale",
      saverZone: "Saver Zone",
      tabbyPlan: "Tabby Plan",
    },

    // About Us Page Content
    aboutUs: {
      title: "Welcome to Ourshopee.com",
      subtitle: "Where Shopping Dreams Come True!",
      description1:
        "Since our inception in 2015, Ourshopee.com has blossomed into one of the leading and fastest-growing online shopping platforms, capturing hearts across the UAE, Oman, Qatar, Kuwait, Bahrain, and KSA. As pioneers in the e-commerce realm, we take pride in being one of the oldest and most trusted names in the industry.",
      description2:
        "At Ourshopee.com, we curate a captivating collection of top-quality products, carefully handpicked to cater to your every desire. From the latest electronics that spark innovation to the trendiest fashion that sets new standards, we have something for everyone, all within the comfort of your fingertips.",
      description3:
        "Our commitment to excellence is unwavering, and our user-friendly interface ensures a seamless and enjoyable shopping experience. Feel secure with our range of trusted payment options and embrace the excitement of swift and reliable deliveries right to your doorstep.",
      description4:
        "Join the millions of satisfied customers who have embarked on an extraordinary journey with Ourshopee.com. Discover the joy of shopping with us, where convenience meets trust, and let your shopping dreams soar. Begin your delightful retail adventure today - Happy shopping!",
      journey: "Ourshopee Journey",
      visions: "Visions",
      visionText:
        "Our vision is to become a globally trusted e-commerce platform where customer needs are fulfilled",
      missions: "Missions",
      missionText:
        "Our mission is to ensure customer satisfaction through faster delivery of genuine products at competitive prices & round the clock services",
      factor1Title: "Quick Market Acquisition",
      factor1Text:
        "Since its birth in UAE 6 years ago, the brand has penetrated Oman, Qatar, Bahrain & Kuwait. Every market is served by a localized app",
      factor2Title: "E-fulfillment Centers",
      factor2Text:
        "Ourshopee will directly control inventory & logistic management to ensure maximum efficiency",
      factor3Title: "BNPL Support",
      factor3Text:
        'BNPL is a tech-enabled payment system where "Buy Now Pay later" is the key and, that too comes with zero interest or cost.',
      factor4Title: "Trusted Ancillary Business",
      factor4Text:
        "Branding out product centered ventures such as Elony Electronics",
      customerFirst: "Customer first",
      customerFirstText:
        "We look at the world from our customers point of view",
      integrity: "Integrity",
      integrityText:
        "We strive to do what is right and do what we say we will do.",
      inclusion: "Inclusion",
      inclusionText:
        "We value the uniqueness in everyone, respect differences, and foster a sense of belonging",
      biasForAction: "Bias for Action",
      biasForActionText:
        "We have a strong sense of urgency to solve problems strategically",
      audacity: "Audacity",
      audacityText: "We think big and take bold bets. We change the paradigm.",
      founderName: "Dr. Shanith Mangalat",
      founderTitle: "Founder & Chairman",
      founderDescription:
        "Dr. Shanith Mangalat is Chairman of DRS holding based in UAE, with Investments in more than 29 operating companies with aggregate annual revenues of more than USD 100 Million. He chairs the boards of several group operating companies, including ourshopee online store, hnc healthcare group, Ruky Perfumes, Medco pharmaceutical distributors. The DRS holding companies include 29 private listed corporates\nDr.Shanith Mangalat is an MBBS Graduate from Yenepoya University, Mangalore, and specialist studies in Family Medicine/ Doctorate of Medicine and Post Graduated in Diabetology from India's prestigious Apollo hospitals, Hyderabad. His business leadership has been recognized by several corporate & community organizations and he has received numerous awards, including",
      achievements: "Achievement's",
    },

    // Form Labels and Placeholders
    forms: {
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      firstName: "First Name",
      lastName: "Last Name",
      fullName: "Full Name",
      phone: "Phone",
      mobile: "Mobile",
      address: "Address",
      city: "City",
      state: "State",
      country: "Country",
      zipCode: "Zip Code",
      postalCode: "Postal Code",
      streetAddress: "Street Address",
      buildingNumber: "Building Number",
      apartmentNumber: "Apartment Number",
      landmark: "Landmark",
      saveAddress: "Save Address",
      enterEmail: "Enter your email",
      enterPassword: "Enter your password",
      enterName: "Enter your name",
      enterPhone: "Enter your phone number",
      selectCountry: "Select Country",
      selectCity: "Select City",
      message: "Message",
      subject: "Subject",
      orderId: "Order ID",
      referenceId: "Reference ID",
      searchPlaceholder: "Search for products...",
    },

    // Product Related
    product: {
      inStock: "In Stock",
      outOfStock: "Out of Stock",
      addToCart: "Add to Cart",
      buyNow: "Buy Now",
      quantity: "Quantity",
      price: "Price",
      originalPrice: "Original Price",
      discountedPrice: "Discounted Price",
      youSave: "You Save",
      rating: "Rating",
      reviews: "Reviews",
      noReviews: "No Reviews",
      writeReview: "Write a Review",
      specifications: "Specifications",
      description: "Description",
      features: "Features",
      relatedProducts: "Related Products",
      recentlyViewed: "Recently Viewed",
      similarProducts: "Similar Products",
      availability: "Availability",
      sku: "SKU",
      brand: "Brand",
      category: "Category",
      freeShipping: "Free Shipping",
      fastDelivery: "Fast Delivery",
      securePayment: "Secure Payment",
    },

    // Cart
    cart: {
      title: "Shopping Cart",
      myCart: "My cart",
      empty: "Your cart is empty",
      emptyDescription: "Your Cart is empty",
      emptySubDescription: "There nothing in the cart. Let's add some items.",
      keepExploring: "Keep exploring",
      continueShopping: "Continue Shopping",
      subtotal: "Subtotal",
      shipping: "Shipping",
      tax: "Tax",
      total: "Total",
      item: "Item",
      items: "Items",
      remove: "Remove",
      qty: "Qty",
      update: "Update",
      proceedToCheckout: "Proceed to Checkout",
      quantity: "Quantity",
      price: "Price",
      loginRegister: "Login/Register",
      loadingMoreOrders: "Loading more orders...",
      noMoreOrders: "No more orders",
    },

    // Orders
    orders: {
      title: "My Orders",
      orderHistory: "Order History",
      noOrders: "You have no orders yet",
      orderId: "Order ID",
      orderDate: "Order Date",
      orderStatus: "Order Status",
      totalAmount: "Total Amount",
      viewDetails: "View Details",
      trackOrder: "Track Order",
      cancelOrder: "Cancel Order",
      reorder: "Reorder",
      pending: "Pending",
      processing: "Processing",
      shipped: "Shipped",
      delivered: "Delivered",
      cancelled: "Cancelled",
      returned: "Returned",
    },

    // Wishlist
    wishlist: {
      title: "My Wishlist",
      empty: "Your wishlist is empty",
      emptyDescription: "Items you save will appear here.",
      remove: "Remove",
      addToCart: "Add to Cart",
    },

    // Checkout and Payment
    checkout: {
      title: "Checkout",
      billingAddress: "Billing Address",
      shippingAddress: "Shipping Address",
      paymentMethod: "Payment Method",
      orderSummary: "Order Summary",
      placeOrder: "Place Order",
      subtotal: "Subtotal",
      shipping: "Shipping",
      tax: "Tax",
      discount: "Discount",
      total: "Total",
      applyCoupon: "Apply Coupon",
      couponCode: "Coupon Code",
      deliveryAddress: "Delivery Address",
      changeAddress: "Change Address",
      selectAddress: "Select Address",
      pleaseSelectDeliveryAddress: "Please select a delivery address!",
    },

    payment: {
      selectPaymentMethod: "Select Payment Method",
      creditCard: "Credit Card",
      debitCard: "Debit Card",
      cashOnDelivery: "Cash on Delivery",
      wallet: "Wallet",
      tabby: "Tabby",
      payNow: "Pay Now",
    },

    // Account
    account: {
      myAccount: "My Account",
      profile: "Profile",
      editPersonalAddress: "Edit and save your personal address",
      personalInformation: "Personal Information",
      addressBook: "Address Book",
      paymentMethods: "Payment Methods",
      orderHistory: "Order History",
      wishlist: "Wishlist",
      settings: "Settings",
      logout: "Logout",
      myOrders: "My Orders",
      myOrdersDescription:
        "View the details of your current and past orders, track your purchases, and stay updated on the status of your items all in one place.",
      myWishlist: "My wishlist",
      myWishlistDescription:
        "Save and manage products you'd love to purchase later.",
      addToCart: "Add to cart",
      trackYourOrder: "Track your order",
      trackYourOrderDescription:
        "Monitor your order and stay updated on its status.",
      trackByReferenceId: "Track by Reference ID",
      manageComplaints: "Manage Complaints",
      manageComplaintsDescription:
        "Place your complaints & Track the status of your complaints.",
      placeComplaint: "Place a complaints",
    },

    // Contact Us Page
    contactUs: {
      mapLocation: "Map Location",
      reachUs: "Reach us",
      phone: "Phone:",
      email: "Email:",
      address: "Address:",
      downloadOurApp: "Download Our App",
    },

    // Messages and Alerts
    messages: {
      success: "Success",
      error: "Error",
      warning: "Warning",
      info: "Info",
      loading: "Loading...",
      saving: "Saving...",
      processing: "Processing...",
      pleaseWait: "Please wait...",
      successMessage: "Operation completed successfully",
      errorMessage: "An error occurred. Please try again.",
      noResults: "No results found",
      tryAgain: "Try Again",
    },

    // Breadcrumbs
    breadcrumbs: {
      home: "Home",
    },

    // Common Labels
    labels: {
      welcome: "Welcome",
      hello: "Hello",
      thankYou: "Thank You",
      sorry: "Sorry",
      yes: "Yes",
      no: "No",
      or: "Or",
      and: "And",
      of: "Of",
      all: "All",
      none: "None",
      select: "Select",
      selected: "Selected",
      optional: "Optional",
      required: "Required",
      readMore: "Read More",
      readLess: "Read Less",
      viewMore: "View More",
      viewLess: "View Less",
      showMore: "Show More",
      showLess: "Show Less",
      new: "New",
      sale: "Sale",
      hot: "Hot",
      bestSeller: "Best Seller",
      featured: "Featured",
      trending: "Trending",
      popular: "Popular",
      latest: "Latest",
    },

    // Header Components
    header: {
      searchPlaceholder: "What are you looking for?",
      cancel: "Cancel",
      noResults: "No results found",
      noTitle: "no title",
      myProfile: "My Profile",
      myOrder: "My Order",
      wishlist: "Wishlist",
      trackOrder: "Track Order",
      address: "Address",
      complaints: "Complaints",
      logout: "Logout",
      login: "Login",
      signup: "Signup",
      welcome: "Welcome",
      categories: "Categories",
      category: "Category",
      shopByCategory: "Shop by Category",
      shopBySubCategory: "Shop by Sub-Category",
      topBrands: "Top Brands",
      noCategoriesFound: "No Categories Found",
      noBrandsFound: "No brands found",
      appBetter: "App–solutely better on the app.",
      androidRating: "4.1★ rating with 500K+ downloads",
      iosAvailable: "Available on iPhone, iPad & Mac",
      takeMeToApp: "Take me to the app.",
      clickHere: "Click here",
      addressNotFound: "Address not found",
      errorFetchingAddress: "Error fetching address",
      locationAccessDenied: "Location access denied",
      geolocationNotSupported: "Geolocation not supported",
      fetchingAddress: "Fetching address...",
      fetchingLocation: "Fetching location...",
    },

    // Special Pages
    specialPages: {
      dealsOfTheDay: "Deals of the Day",
      flashSale: "Flash Sale",
      clearance: "Clearance",
      bundleDeals: "Bundle Deals",
      topSelling: "Top Selling",
      saverZone: "Saver zone",
      clearanceDeals: "Clearance Deals",
      excitingOffers: "Exciting Offers",
      shopByTopBrands: "Shop By Top Brands",
      browsePopularCategories: "Browse Popular Categories",
      topPicks: "Top Picks",
      brandOfTheWeek: "Brand of the Week",
      brandOfTheWeekShort: "BRAND OF THE WEEK",
      theWeek: "THE WEEK",
      justDropped: "Just Dropped",
      limitedOffer: "Limited Offer",
      stealTheDeal: "Steal the Deal",
    },
  },

  ar: {
    // Navigation
    nav: {
      home: "الرئيسية",
      categories: "الفئات",
      brands: "العلامات التجارية",
      deals: "العروض",
      clearance: "تخفيضات",
      sellWithUs: "بيع معنا",
      trackOrder: "تتبع طلبك",
      myAccount: "حسابي",
      myOrders: "طلباتي",
      myWishlist: "قائمة الأمنيات",
      cart: "السلة",
      login: "تسجيل الدخول",
      logout: "تسجيل الخروج",
      register: "التسجيل",
      search: "بحث",
      searchPlaceholder: "ابحث عن المنتجات...",
      deliverTo: "التوصيل إلى",
      downloadApp: "تنزيل التطبيق",
    },

    // Footer
    footer: {
      aboutUs: "من نحن",
      connectWithUs: "تواصل معنا",
      enterYourMail: "أدخل بريدك الإلكتروني",
      keepInTouch: "ابق على تواصل",
      customerService: "خدمة العملاء",
      quickLinks: "روابط سريعة",
      categories: "الفئات",
      information: "معلومات",
      aboutCompany:
        "الإمارات وأكثر! تأسست Ourshopee.com في عام 2015، واعتزت نفسها كمنصة تسوق عبر الإنترنت بارزة وسريعة النمو في المنطقة...",
      contactUs: "اتصل بنا",
      faqs: "الأسئلة الشائعة",
      privacyPolicy: "سياسة الخصوصية",
      termsAndConditions: "الشروط والأحكام",
      returnPolicy: "سياسة الإرجاع",
      returnAndReplacementPolicy: "سياسة الإرجاع والاستبدال",
      sitemap: "خريطة الموقع",
      affiliateProgram: "برنامج الإحالة",
      sellWithUs: "بيع معنا",
      placeComplaint: "تقديم شكوى",
      manageComplaint: "إدارة الشكوى",
      complaints: "الشكاوى",
      trackYourOrder: "تتبع طلبك",
      changePassword: "تغيير كلمة المرور",
      deliveryAddress: "عنوان التوصيل",
      address: "العنوان",
      onboarding: "التوجيه",
    },

    // Common Buttons and Actions
    buttons: {
      addToCart: "أضف إلى السلة",
      buyNow: "اشتري الآن",
      viewDetails: "عرض التفاصيل",
      addToWishlist: "أضف إلى قائمة الأمنيات",
      removeFromWishlist: "احذف من قائمة الأمنيات",
      proceedToCheckout: "المتابعة للدفع",
      continueShopping: "متابعة التسوق",
      placeOrder: "تأكيد الطلب",
      apply: "تطبيق",
      submit: "إرسال",
      save: "حفظ",
      cancel: "إلغاء",
      delete: "حذف",
      edit: "تعديل",
      update: "تحديث",
      confirm: "تأكيد",
      back: "رجوع",
      next: "التالي",
      previous: "السابق",
      close: "إغلاق",
      search: "بحث",
      filter: "تصفية",
      sort: "ترتيب",
      clear: "مسح",
      reset: "إعادة تعيين",
      loadMore: "تحميل المزيد",
      showMore: "عرض المزيد",
      showLess: "عرض أقل",
      select: "اختر",
      remove: "إزالة",
      viewAll: "عرض الكل",
    },

    // Page Titles
    pages: {
      home: "الرئيسية",
      aboutUs: "من نحن",
      aboutOurshopee: "من نحن",
      contactUs: "اتصل بنا",
      faqs: "الأسئلة الشائعة",
      privacyPolicy: "سياسة الخصوصية",
      termsAndConditions: "الشروط والأحكام",
      returnPolicy: "سياسة الإرجاع",
      returnAndReplacementPolicy: "سياسة الإرجاع والاستبدال",
      sitemap: "خريطة الموقع",
      affiliateProgram: "برنامج الإحالة",
      sellWithUs: "بيع معنا",
      seller: "البائع",
      complaints: "الشكاوى",
      placeComplaint: "تقديم شكوى",
      manageComplaint: "إدارة الشكوى",
      successComplaint: "نجحت الشكوى",
      trackYourOrder: "تتبع طلبك",
      trackOrderById: "تتبع الطلب بالرقم",
      trackOrderByReferenceId: "تتبع الطلب برقم المرجع",
      myAccount: "حسابي",
      myOrders: "طلباتي",
      myWishlist: "قائمة الأمنيات",
      changePassword: "تغيير كلمة المرور",
      deliveryAddress: "عنوان التوصيل",
      address: "العنوان",
      cart: "السلة",
      checkout: "الدفع",
      payment: "الدفع",
      order: "الطلب",
      brands: "العلامات التجارية",
      categories: "الفئات",
      productsCategory: "فئة المنتجات",
      productsSubcategory: "الفئة الفرعية للمنتجات",
      clearance: "تخفيضات",
      deals: "العروض",
      dealsOfTheDay: "عروض اليوم",
      bundleDeals: "عروض الباقات",
      perfumes: "العطور",
      searchResult: "نتائج البحث",
      onboarding: "التوجيه",
      notFound: "الصفحة غير موجودة",
      mobileFest: "مهرجان الموبايل",
      timeFest: "مهرجان الوقت",
      tvSuperSale: "تخفيضات التلفزيون الكبرى",
      saverZone: "منطقة التوفير",
      tabbyPlan: "خطة تابي",
    },

    // About Us Page Content
    aboutUs: {
      title: "مرحباً بك في Ourshopee.com",
      subtitle: "حيث تتحقق أحلام التسوق!",
      description1:
        "منذ تأسيسنا في عام 2015، نمت Ourshopee.com لتصبح واحدة من منصات التسوق عبر الإنترنت الرائدة والأسرع نمواً، حيث احتلت القلوب عبر الإمارات وعمان وقطر والكويت والبحرين والسعودية. كرواد في عالم التجارة الإلكترونية، نفخر بأننا أحد أقدم الأسماء وأكثرها ثقة في الصناعة.",
      description2:
        "في Ourshopee.com، نقوم بتنظيم مجموعة رائعة من المنتجات عالية الجودة، والتي تم اختيارها بعناية لتلبية كل رغباتك. من أحدث الأجهزة الإلكترونية التي تشعل الابتكار إلى أحدث الموضات التي تحدد معايير جديدة، لدينا شيء للجميع، كل ذلك في متناول يدك.",
      description3:
        "التزامنا بالتميز لا يتزعزع، وواجهتنا سهلة الاستخدام تضمن تجربة تسوق سلسة وممتعة. اشعر بالأمان مع مجموعة خيارات الدفع الموثوقة لدينا واستمتع بإثارة التسليمات السريعة والموثوقة مباشرة إلى عتبة دارك.",
      description4:
        "انضم إلى ملايين العملاء الراضين الذين بدأوا رحلة استثنائية مع Ourshopee.com. اكتشف متعة التسوق معنا، حيث تلتقي الراحة بالثقة، ودع أحلام التسوق ترتفع. ابدأ مغامرة التسوق الساحرة اليوم - تسوق سعيد!",
      journey: "رحلة Ourshopee",
      visions: "الرؤية",
      visionText:
        "رؤيتنا هي أن نصبح منصة تجارة إلكترونية موثوقة عالمياً حيث يتم تلبية احتياجات العملاء",
      missions: "المهمة",
      missionText:
        "مهمتنا هي ضمان رضا العملاء من خلال توصيل أسرع للمنتجات الأصيلة بأسعار تنافسية وخدمات على مدار الساعة",
      factor1Title: "اكتساب السوق السريع",
      factor1Text:
        "منذ ولادتها في الإمارات قبل 6 سنوات، اخترقت العلامة التجارية عمان وقطر والبحرين والكويت. يتم تقديم كل سوق من خلال تطبيق محلي",
      factor2Title: "مراكز الوفاء الإلكتروني",
      factor2Text:
        "ستتحكم Ourshopee مباشرة في إدارة المخزون واللوجستيات لضمان أقصى كفاءة",
      factor3Title: "دعم BNPL",
      factor3Text:
        'BNPL هو نظام دفع مدعوم بالتكنولوجيا حيث "اشتري الآن وادفع لاحقاً" هو المفتاح، وذلك أيضاً بدون فائدة أو تكلفة.',
      factor4Title: "الأعمال المساعدة الموثوقة",
      factor4Text:
        "بناء العلامات التجارية للمشاريع المتمركزة حول المنتجات مثل Elony Electronics",
      customerFirst: "العميل أولاً",
      customerFirstText: "ننظر إلى العالم من وجهة نظر عملائنا",
      integrity: "النزاهة",
      integrityText:
        "نسعى جاهدين للقيام بما هو صحيح والقيام بما نقول أننا سنفعله.",
      inclusion: "الشمولية",
      inclusionText:
        "نقدر التفرد في الجميع، ونحترم الاختلافات، ونعزز الشعور بالانتماء",
      biasForAction: "الميل للعمل",
      biasForActionText: "لدينا شعور قوي بالإلحاح لحل المشاكل بشكل استراتيجي",
      audacity: "الجسارة",
      audacityText: "نفكر بشكل كبير ونتخذ رهانات جريئة. نغير النموذج.",
      founderName: "الدكتور شانيث مانجالات",
      founderTitle: "المؤسس والرئيس",
      founderDescription:
        "الدكتور شانيث مانجالات هو رئيس مجلس إدارة DRS القابضة ومقرها في الإمارات، مع استثمارات في أكثر من 29 شركة تشغيلية بإيرادات سنوية إجمالية تزيد عن 100 مليون دولار أمريكي. يترأس مجالس إدارة العديد من شركات المجموعة التشغيلية، بما في ذلك متجر ourshopee عبر الإنترنت، ومجموعة hnc للرعاية الصحية، وعطور Ruky، وموزعي Medco الصيدلانيين. تشمل شركات DRS القابضة 29 شركة خاصة مدرجة\nالدكتور شانيث مانجالات خريج MBBS من جامعة Yenepoya، مانجالور، ودراسات متخصصة في طب الأسرة/دكتوراه في الطب وتخرج من كلية الدراسات العليا في طب السكري من مستشفيات Apollo المرموقة في الهند، حيدر أباد. تم الاعتراف بقيادته التجارية من قبل العديد من المنظمات التجارية والمجتمعية وحصل على العديد من الجوائز، بما في ذلك",
      achievements: "الإنجازات",
    },

    // Form Labels and Placeholders
    forms: {
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      fullName: "الاسم الكامل",
      phone: "الهاتف",
      mobile: "الجوال",
      address: "العنوان",
      city: "المدينة",
      state: "الولاية",
      country: "الدولة",
      zipCode: "الرمز البريدي",
      postalCode: "الرمز البريدي",
      streetAddress: "عنوان الشارع",
      buildingNumber: "رقم المبنى",
      apartmentNumber: "رقم الشقة",
      landmark: "معلم بارز",
      saveAddress: "حفظ العنوان",
      enterEmail: "أدخل بريدك الإلكتروني",
      enterPassword: "أدخل كلمة المرور",
      enterName: "أدخل اسمك",
      enterPhone: "أدخل رقم الهاتف",
      selectCountry: "اختر الدولة",
      selectCity: "اختر المدينة",
      message: "الرسالة",
      subject: "الموضوع",
      orderId: "رقم الطلب",
      referenceId: "رقم المرجع",
      searchPlaceholder: "ابحث عن المنتجات...",
    },

    // Product Related
    product: {
      inStock: "متوفر",
      outOfStock: "غير متوفر",
      addToCart: "أضف إلى السلة",
      buyNow: "اشتري الآن",
      quantity: "الكمية",
      price: "السعر",
      originalPrice: "السعر الأصلي",
      discountedPrice: "السعر المخفض",
      youSave: "توفر",
      rating: "التقييم",
      reviews: "التقييمات",
      noReviews: "لا توجد تقييمات",
      writeReview: "اكتب تقييم",
      specifications: "المواصفات",
      description: "الوصف",
      features: "الميزات",
      relatedProducts: "منتجات ذات صلة",
      recentlyViewed: "شوهدت مؤخراً",
      similarProducts: "منتجات مشابهة",
      availability: "التوفر",
      sku: "رمز المنتج",
      brand: "العلامة التجارية",
      category: "الفئة",
      freeShipping: "شحن مجاني",
      fastDelivery: "توصيل سريع",
      securePayment: "دفع آمن",
    },

    // Cart
    cart: {
      title: "سلة التسوق",
      myCart: "سلتي",
      empty: "سلة التسوق فارغة",
      emptyDescription: "سلتك فارغة",
      emptySubDescription: "لا يوجد شيء في السلة. دعنا نضيف بعض العناصر.",
      keepExploring: "استمر في الاستكشاف",
      continueShopping: "متابعة التسوق",
      subtotal: "المجموع الفرعي",
      shipping: "الشحن",
      tax: "الضريبة",
      total: "المجموع",
      item: "عنصر",
      items: "عناصر",
      remove: "إزالة",
      qty: "الكمية",
      update: "تحديث",
      loginRegister: "تسجيل الدخول/التسجيل",
      loadingMoreOrders: "جاري تحميل المزيد من الطلبات...",
      noMoreOrders: "لا مزيد من الطلبات",
      proceedToCheckout: "المتابعة للدفع",
      quantity: "الكمية",
      price: "السعر",
    },

    // Orders
    orders: {
      title: "طلباتي",
      orderHistory: "سجل الطلبات",
      noOrders: "ليس لديك طلبات بعد",
      orderId: "رقم الطلب",
      orderDate: "تاريخ الطلب",
      orderStatus: "حالة الطلب",
      totalAmount: "المبلغ الإجمالي",
      viewDetails: "عرض التفاصيل",
      trackOrder: "تتبع الطلب",
      cancelOrder: "إلغاء الطلب",
      reorder: "إعادة الطلب",
      pending: "قيد الانتظار",
      processing: "قيد المعالجة",
      shipped: "تم الشحن",
      delivered: "تم التسليم",
      cancelled: "ملغى",
      returned: "مرجع",
    },

    // Wishlist
    wishlist: {
      title: "قائمة الأمنيات",
      empty: "قائمة الأمنيات فارغة",
      emptyDescription: "العناصر التي تحفظها ستظهر هنا.",
      remove: "إزالة",
      addToCart: "أضف إلى السلة",
    },

    // Checkout and Payment
    checkout: {
      title: "الدفع",
      billingAddress: "عنوان الفوترة",
      shippingAddress: "عنوان الشحن",
      paymentMethod: "طريقة الدفع",
      orderSummary: "ملخص الطلب",
      placeOrder: "تأكيد الطلب",
      subtotal: "المجموع الفرعي",
      shipping: "الشحن",
      tax: "الضريبة",
      discount: "الخصم",
      total: "المجموع",
      applyCoupon: "تطبيق كوبون",
      couponCode: "رمز الكوبون",
      deliveryAddress: "عنوان التوصيل",
      changeAddress: "تغيير العنوان",
      selectAddress: "اختر العنوان",
      pleaseSelectDeliveryAddress: "يرجى اختيار عنوان التوصيل!",
    },

    payment: {
      selectPaymentMethod: "اختر طريقة الدفع",
      creditCard: "بطاقة ائتمان",
      debitCard: "بطاقة خصم",
      cashOnDelivery: "الدفع عند الاستلام",
      wallet: "المحفظة",
      tabby: "تابي",
      payNow: "ادفع الآن",
    },

    // Account
    account: {
      myAccount: "حسابي",
      profile: "الملف الشخصي",
      editPersonalAddress: "تحرير وحفظ عنوانك الشخصي",
      personalInformation: "المعلومات الشخصية",
      addressBook: "دفتر العناوين",
      paymentMethods: "طرق الدفع",
      orderHistory: "سجل الطلبات",
      wishlist: "قائمة الأمنيات",
      settings: "الإعدادات",
      logout: "تسجيل الخروج",
      myOrders: "طلباتي",
      myOrdersDescription:
        "اطلع على تفاصيل طلباتك الحالية والسابقة، وتتبع مشترياتك، وابق محدثًا حول حالة العناصر في مكان واحد.",
      myWishlist: "قائمة أمنياتي",
      myWishlistDescription: "احفظ وأدر المنتجات التي ترغب في شرائها لاحقًا.",
      addToCart: "أضف إلى السلة",
      trackYourOrder: "تتبع طلبك",
      trackYourOrderDescription: "راقب طلبك وابق محدثًا حول حالته.",
      trackByReferenceId: "تتبع برقم المرجع",
      manageComplaints: "إدارة الشكاوى",
      manageComplaintsDescription: "قدم شكواك وتتبع حالة شكواك.",
      placeComplaint: "تقديم شكوى",
    },

    // Contact Us Page
    contactUs: {
      mapLocation: "موقع الخريطة",
      reachUs: "تواصل معنا",
      phone: "الهاتف:",
      email: "البريد الإلكتروني:",
      address: "العنوان:",
      downloadOurApp: "قم بتنزيل تطبيقنا",
    },

    // Messages and Alerts
    messages: {
      success: "نجح",
      error: "خطأ",
      warning: "تحذير",
      info: "معلومة",
      loading: "جاري التحميل...",
      saving: "جاري الحفظ...",
      processing: "جاري المعالجة...",
      pleaseWait: "يرجى الانتظار...",
      successMessage: "تمت العملية بنجاح",
      errorMessage: "حدث خطأ. يرجى المحاولة مرة أخرى.",
      noResults: "لم يتم العثور على نتائج",
      tryAgain: "حاول مرة أخرى",
    },

    // Breadcrumbs
    breadcrumbs: {
      home: "الرئيسية",
    },

    // Common Labels
    labels: {
      welcome: "مرحباً",
      hello: "مرحباً",
      thankYou: "شكراً لك",
      sorry: "آسف",
      yes: "نعم",
      no: "لا",
      or: "أو",
      and: "و",
      of: "من",
      all: "الكل",
      none: "لا شيء",
      select: "اختر",
      selected: "محدد",
      optional: "اختياري",
      required: "مطلوب",
      readMore: "اقرأ المزيد",
      readLess: "اقرأ أقل",
      viewMore: "عرض المزيد",
      viewLess: "عرض أقل",
      showMore: "عرض المزيد",
      showLess: "عرض أقل",
      new: "جديد",
      sale: "تخفيض",
      hot: "ساخن",
      bestSeller: "الأكثر مبيعاً",
      featured: "مميز",
      trending: "رائج",
      popular: "شائع",
      latest: "الأحدث",
    },

    // Header Components
    header: {
      searchPlaceholder: "ماذا تبحث عنه؟",
      cancel: "إلغاء",
      noResults: "لم يتم العثور على نتائج",
      noTitle: "لا يوجد عنوان",
      myProfile: "ملفي الشخصي",
      myOrder: "طلبي",
      wishlist: "قائمة الأمنيات",
      trackOrder: "تتبع الطلب",
      address: "العنوان",
      complaints: "الشكاوى",
      logout: "تسجيل الخروج",
      login: "تسجيل الدخول",
      signup: "التسجيل",
      welcome: "مرحباً",
      categories: "الفئات",
      category: "الفئة",
      shopByCategory: "تسوق حسب الفئة",
      shopBySubCategory: "تسوق حسب الفئة الفرعية",
      topBrands: "أفضل العلامات التجارية",
      noCategoriesFound: "لم يتم العثور على فئات",
      noBrandsFound: "لم يتم العثور على علامات تجارية",
      appBetter: "أفضل بكثير على التطبيق.",
      androidRating: "تقييم 4.1★ مع أكثر من 500 ألف تحميل",
      iosAvailable: "متاح على iPhone و iPad و Mac",
      takeMeToApp: "خذني إلى التطبيق.",
      clickHere: "انقر هنا",
      addressNotFound: "لم يتم العثور على العنوان",
      errorFetchingAddress: "خطأ في جلب العنوان",
      locationAccessDenied: "تم رفض الوصول إلى الموقع",
      geolocationNotSupported: "الموقع الجغرافي غير مدعوم",
      fetchingAddress: "جاري جلب العنوان...",
      fetchingLocation: "جاري جلب الموقع...",
    },

    // Special Pages
    specialPages: {
      dealsOfTheDay: "عروض اليوم",
      flashSale: "تخفيضات سريعة",
      clearance: "تخفيضات",
      bundleDeals: "عروض الباقات",
      topSelling: "الأكثر مبيعاً",
      saverZone: "منطقة التوفير",
      clearanceDeals: "صفقات التخفيضات",
      excitingOffers: "عروض مثيرة",
      shopByTopBrands: "تسوق حسب أفضل العلامات التجارية",
      browsePopularCategories: "تصفح الفئات الشائعة",
      topPicks: "أفضل الخيارات",
      brandOfTheWeek: "علامة الأسبوع",
      brandOfTheWeekShort: "علامة",
      theWeek: "الأسبوع",
      justDropped: "وصل للتو",
      limitedOffer: "عرض محدود",
      stealTheDeal: "اغتنم العرض",
    },
  },
};
